### ISSUE TITLE
The error in to_visual.py

### ISSUE THREAD

**Issue by lilybud** [Juanhui28/RepPool#1]
hi, this is an excelent paper. i have a question about the visualition of  graphs. 
when i run the to_visual.py, the console will present the error, like this:
> `Traceback (most recent call last):
>  File "D:/Pycharm Project/RepPool-master/RepPool-master/RepPool/to_visual.py", line 18, in <module>
> a = pickle.load(fp)
> _pickle.UnpicklingError: STACK_GLOBAL requires str
> Backend TkAgg is interactive backend. Turning interactive mode on.`

can you give some advice about this problem? thank you ~

**Comment by Juanhui28** [comment]
> hi, this is an excelent paper. i have a question about the visualition of graphs.
> when i run the to_visual.py, the console will present the error, like this:
> 
> > `Traceback (most recent call last): File "D:/Pycharm Project/RepPool-master/RepPool-master/RepPool/to_visual.py", line 18, in <module> a = pickle.load(fp) _pickle.UnpicklingError: STACK_GLOBAL requires str Backend TkAgg is interactive backend. Turning interactive mode on.`
> 
> can you give some advice about this problem? thank you ~

Hi, hope you have solved this issue.
It seems the error is for loading the .npy file. https://stackoverflow.com/questions/40518780/how-to-np-loads-an-np-saved-array/40518804#40518804   this link might be help.

**Comment by Juanhui28** [comment]
@lilybud 

Hi, hope you have solved this issue.
It seems the error occurs when loading the .npy file. https://stackoverflow.com/questions/40518780/how-to-np-loads-an-np-saved-array/40518804#40518804 this link might  help.
